var allsymbols = new pedigree.Pedigree();
allsymbols.data = {
  1: [
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'Papa Bear'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'Mama Bear'})],
  2: [
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'M'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'F'}),
    new pedigree.Node({'gender': 'nogender',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'NoG'}),
    new pedigree.Node({'gender': 'pregloss',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Pregloss'}),
    new pedigree.Node({'gender': 'male',
                       'affected': true,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Aff'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 0,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Dummy'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': true,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Carr'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Dead'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 2,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': '2 ppl'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 10,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'n ppl'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': true,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Preg'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': true,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Twin F 1'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'Twin F 2'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': true,
                       'parents': [0, 1, 1, 1],
                       'label': 'Proband'})
  ]
};

allsymbols.unions = [
  [1, 1, 0, 1]];

allsymbols.text = 'All symbols test.';

allsymbols.describe_all();

for (var y1 in allsymbols.data) {
  var row = allsymbols.data[y1];
  for (var x1 = 0; x1 < row.length; x1++) {
    allsymbols.describe(x1, y1);
    allsymbols.longdescribe(x1, y1);
    console.log('');
  }
}

allsymbols.plot();
