
var tu2 = new pedigree.Pedigree();
tu2.data = {
  1: [
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'd. 84 natural causes'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'd. 85 natural causes'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'no information about death or cause'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'no information about death or cause'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'd. 70\'s heart problems'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': ''}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'd. 60\'s, mi'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': null,
                       'label': 'd. 60\'s heart failure'})],
  2: [
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 4,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label':
        'A&W, no information about number of children'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': 'A&W, no information about children'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [0, 1, 1, 1],
                       'label': '69 YO, A&W'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 1, 3, 1],
                       'label': '70, diabetes'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 1, 3, 1],
                       'label':
        'd. 65 liver CA, no information about children'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 1, 3, 1],
                       'label': 'd. 73 heart failure'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 1, 3, 1],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'nogender',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 10,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [4, 1, 5, 1],
                       'label':
        'no information about health and number of children / grandchildren'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [4, 1, 5, 1],
                       'label': 'no contact, no health information'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [6, 1, 7, 1],
                       'label':
        '54 YO, fibromyalgia, diabetes, osteoarthritis'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': true,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [6, 1, 7, 1],
                       'label': 'd. 20\'s in Vietnam war'})],
  3: [
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 2,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 2, 3, 2],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 2, 3, 2],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 2,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 2, 3, 2],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 2, 3, 2],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [2, 2, 3, 2],
                       'label': 'born with cleft lip and palate'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [8, 2, 9, 2],
                       'label':
        'seizure disorder dxd 2005, on keppra, fibromyalgia, ' +
        'taking effexer and nortryptoline'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [8, 2, 9, 2],
                       'label': 'A&W'}),
    new pedigree.Node({'gender': 'male',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [8, 2, 9, 2],
                       'label': 'A&W'})],
  4: [
    new pedigree.Node({'gender': 'pregloss',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 4,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [4, 3, 5, 3],
                       'label': 'loss at 8-9 weeks'}),
    new pedigree.Node({'gender': 'female',
                       'affected': false,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': false,
                       'parents': [4, 3, 5, 3],
                       'label': '2 YO A&W'}),
    new pedigree.Node({'gender': 'female',
                       'affected': true,
                       'carrier': false,
                       'dead': false,
                       'multiple': 1,
                       'pregnancy': false,
                       'twin': false,
                       'proband': true,
                       'parents': [4, 3, 5, 3],
                       'label': '***REMOVED*** ***REMOVED***, bilateral cleft lip' +
                                ' and palate.'})
  ]
};

tu2.unions = [
  [1, 1, 0, 1],
  [5, 3, 4, 3],
  [9, 2, 8, 2],
  [7, 1, 6, 1],
  [3, 2, 2, 2],
  [2, 1, 3, 1],
  [5, 1, 4, 1]];

tu2.text = '***REMOVED***Patient Name: ***REMOVED*** Tucker ***REMOVED***; Ethnicity Maternal: Norwegian Paternal: Norwegian; Consanguinity denied';
